export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CREATE_INSTRUCTOR = 'CREATE_INSTRUCTOR';
export const CREATE_STUDENT = 'CREATE_STUDENT';
