export const LOGIN_STUDENT = 'LOGIN_STUDENT';
export const LOGIN_STUDENT_REQUEST = 'LOGIN_STUDENT_REQUEST';
export const LOGIN_STUDENT_SUCCESS = 'LOGIN_STUDENT_SUCCESS';
export const LOGIN_STUDENT_FAILURE = 'LOGIN_STUDENT_FAILURE';

export const LOGIN_INSTRUCTOR = 'LOGIN_INSTRUCTOR';
export const LOGIN_INSTRUCTOR_REQUEST = 'LOGIN_INSTRUCTOR_REQUEST';
export const LOGIN_INSTRUCTOR_SUCCESS = 'LOGIN_INSTRUCTOR_SUCCESS';
export const LOGIN_INSTRUCTOR_FAILURE = 'LOGIN_INSTRUCTOR_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CREATE_STUDENT = 'CREATE_STUDENT';
export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAILURE = 'CREATE_STUDENT_FAILURE';

export const CREATE_INSTRUCTOR = 'CREATE_INSTRUCTOR';
export const CREATE_INSTRUCTOR_REQUEST = 'CREATE_INSTRUCTOR_REQUEST';
export const CREATE_INSTRUCTOR_SUCCESS = 'CREATE_INSTRUCTOR_SUCCESS';
export const CREATE_INSTRUCTOR_FAILURE = 'CREATE_INSTRUCTOR_FAILURE';

export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
